name: Terraform CI/CD

on:
  push:
    branches: [ "dev", "test"]
    paths:
      - 'envs/**'
      - 'modules/**'
  pull_request:
    branches: [ "dev", "test"]
    paths:
      - 'envs/**'
      - 'modules/**'
  workflow_dispatch:
    inputs:
      environment:
        description: "Entorno a desplegar (main)"
        required: true
        default: "main"
permissions:
 contents: 'read'
 issues: 'write' 
jobs:
  terraform:
    name: Terraform ${{ github.ref_name }} CI/CD
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1  # Cambiar si usás otra región

    defaults:
      run:
        working-directory: envs/${{ github.event.inputs.environment || github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        
      - name: Terraform Apply (solo dev y test)
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/test'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

      - name: Terraform Apply (solo main/prod)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
